# List the coordinates of the chest locations here
# Only 1 block of the double chest needs to be put here
# Format: [world],[x],[y],[z]
locations:
  - "world,0,100,0"
  - "world,3,100,0"
  - "world,5,100,0"
    
# Enter gruops and their associated permissions here
# List in order of priority: The group of the player
# is the first one that they have permission for.
groups:
  pd: "ac.pd"
  ambulance: "ac.omsz"
  mechanic: "ac.mechanic"
  agency: "ac.ea"

# Each item has a slot, item, name, and lore.
# The slot and item options are mandatory. 
# Slot is 0 indexed, meaning the first slot in the inventory is 0
# the lore option must be a list of text
main-menu:
  title: "AFR Menu"
  deposit:
    slot: 11
    item: PAPER
    name: "&cDeposit"
    lore:
    - ""
    - ""
  withdraw:
    slot: 13
    item: SUNFLOWER
    name: "&eWithdraw"
    lore:
    - ""
    - ""
  shop:
    slot: 15
    item: EMERALD
    name: "&aShop"
    lore:
    - ""
    - ""
    
# This item will fill the main menu, and also the bottom of each GUI
fill-item:
  item: LIGHT_BLUE_STAINED_GLASS_PANE
  name: ""
# To previous page
previous-page:
  item: ARROW
  name: "&fLast Page"
  slot: 45
# To next page
next-page:
  item: ARROW
  name: "&fNext Page"
  slot: 53
    
deposit-menu:
  title: "&cDeposit"
  confirm: 
    name: "&aConfirm"
    item: "GREEN_STAINED_GLASS_PANE"
    slot: 49
  back-item:
    name: "&cBack"
    item: "BARRIER"
    slot: 53
    
withdraw-menu:
  title: "&eWithdraw"
  # These lines will be added to the end of each shop item
  # %name% for item name, %amount% for total item amount
  name-format: "%name% &ax%amount%"
  # These lines will be added to the end of each shop item
  withdraw-format:
    - ""
    - "&cLeft-click &7to withdraw &6%left-click-amount%"
    - "&cRight-click &7to withdraw &6%right-click-amount%"
    - "&cShift + Left-click &7to withdraw &61 stack"
  left-click-amount: 1
  right-click-amount: 8
  back-item:
    name: "&cBack"
    item: "BARRIER"
    # The slot must not be 45 or 53
    slot: 49
  
shop-menu:
  title: "&aShop"
  # These lines will be added to the end of each shop item
  cost-format:
    - ""
    - "&7Cost: &b$%cost%"
    - "&cLeft-click &7to buy &6%left-click-amount%"
    - "&cRight-click &7to buy &6%right-click-amount%"
    - "&cShift + Left-click &7to buy &61 stack"
  left-click-amount: 1
  right-click-amount: 8
  back-item:
    name: "&cBack"
    item: "BARRIER"
    # The slot must not be 45 or 53
    slot: 49
  shops:
    # each section should have same name as one of the groups defined above
    pd:
      # The key doesn't have to be a number
      # Pageination is supported if amount of items goes above 45
      1: 
        item: COOKED_BEEF
        cost: 64
      2:
        item: IRON_SWORD
        cost: 143
        
messages:
  no-group: "&cYou are not in a faction!"
  items-deposited: "&7You deposited &a%amount% &7items."
  not-enough-money: "&cYou do not have enough money (%cost%) for this transaction."
  purchase-successful: "&aYou bought %amount%x %name% for %cost%."
  inventory-full: "&cYour inventory is full!"
    